# Generated by Django 3.2 on 2021-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrační_značka_automobilu', models.CharField(max_length=100)),
                ('datum_poslední_technické_kontroly', models.DateField()),
                ('značka_a_typ_vozidla', models.CharField(max_length=1000)),
                ('počet_najetých_kilometrů', models.IntegerField()),
            ],
        ),
    ]
