# Generated by Django 3.2 on 2021-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('číslo_řidičského_průkazu', models.CharField(max_length=100)),
                ('datum_narození', models.DateField()),
                ('jméno_a_přijímení', models.CharField(max_length=1000)),
            ],
        ),
    ]
